"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:aqua)\
[ ](fg:fg0 bg:aqua)$character$username\
[](fg:aqua bg:blue)\
$directory\
[](fg:blue bg:purple)\
[ ](fg:fg0 bg:purple)($git_branch[ ](fg:fg0 bg:purple)$git_status)\
[ ](fg:purple)\
"""

palette = 'nya'

[palettes.nya]
fg0 = '#fcf4ed'#'#E1E7DD'
fg1 = '#d3c6aa'
blue = '#7FBBB3'
aqua = '#83C092'
green = '#A7C080'
purple = '#D699B6'
red = '#E67E80'
orange = '#E69875'
yellow = '#DBBC7F'

[username]
show_always = true
style_user = "bg:aqua fg:fg0"
style_root = "bg:red fg:fg0"
format = '[$user]($style)'

[directory]
style = "fg:fg0 bg:blue"
format = "[$path]($style)"
truncation_length = 300
fish_style_pwd_dir_length = 1

[git_branch]
symbol = ""
format = '[$symbol $branch](fg:fg0 bg:purple)'

[git_status]
format = '[($all_status$ahead_behind )](fg:fg0 bg:purple)'

[character]
disabled = false
format = "$symbol"
success_symbol = '[󰛢 ](bg:aqua bold fg:fg0)'
error_symbol = '[ ](bg:aqua bold fg:red)'
vimcmd_symbol = '[](bg:aqua bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bg:aqua bold fg:color_purple)'
vimcmd_replace_symbol = '[](bg:aqua bold fg:color_purple)'
vimcmd_visual_symbol = '[](bg:aqua bold fg:color_yellow)'

[line_break]
disabled = true

[time]
disabled = true
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[os]
disabled = true

[nodejs]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cpp]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[php]
disabled = true

[java]
disabled = true

[kotlin]
disabled = true

[haskell]
disabled = true

[python]
disabled = true

[docker_context]
disabled = true

[conda]
disabled = true

[pixi]
disabled = true
