"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:seg1)\
[ ](fg:fg0 bg:seg1)$character$username\
$hostname\
[ ](fg:seg1)\
[](fg:seg2)\
$directory\
[](fg:seg2 bg:seg3)\
[ ](fg:fg0 bg:seg3)\
($git_branch[ ](fg:fg0 bg:seg3))\
[](fg:seg3 bg:seg4)\
[ ](bg:seg4 fg:fg0)$nix_shell\
[ ](fg:seg4)\
"""
#
#

# [](fg:seg3 bg:seg4)\
# [ ](bg:seg4 fg:fg0)$nix_shell\

palette = 'volcanic_shale_deep'

[palettes.kelp_forest_shallow] #    fish:"solarized"  kitty:"Everforest Light Hard"
fg0  = '#ffffff'
seg1 = '#6d9ba7'#7c9ca4 #6d9ba7
seg2 = '#7c9f8b'#82a390 #7c9f8b
seg3 = '#b7be84'#b7be84 #b7be84
seg4 = '#c2a37b'#c2a37b #c2a37b
err  = '#7a2e2a'
root = '#b37772'
vim0 = '#2f5a3c'
vim1 = '#6b3a63'
vim2 = '#6b4610'

# old
# seg1 = '#7395a6'
# seg2 = '#7ca294'
# seg3 = '#b8a284'
# seg4 = '#b8a284'

[palettes.volcanic_shale_deep] #    fish:"catppuccin-macchiato"  kitty:"Catppuccin-Macchiato"
fg0 = '#f0e3da'
seg1 = '#565e7b'
seg2 = '#5c505f'
seg3 = '#93677a'
seg4 = '#937a7a'
err = '#ef8079'
root = '#9e3b33'
vim0 = '#e5c890'
vim1 = '#ca9ee6'
vim2 = '#ef9f76'

# old
# seg1 = '#565e7b'
# seg2 = '#5f5361'
# seg3 = '#93677a'
# seg4 = '#937667'

# seg1 = '#56677b'
# seg2 = '#5a5361'
# seg3 = '#936786'
# seg4 = '#937a7a'

[palettes.kelp_forest_deep] #  fish:"solarized"  kitty:"Everforest Light Hard"
fg0  = '#dce6e2'
seg1 = '#4b728b'
seg2 = '#588778'
seg3 = '#b38C5f'
err  = '#ee9a94'
root = '#9e4b48'
vim0 = '#a7c080'
vim1 = '#d699b6'
vim2 = '#dbbc7f'

[palettes.volcanic_shale_surface] #  fish:"solarized"  kitty:"Everforest Light Hard"
fg0  = '#ffffff'
seg1 = '#7f879f'
seg2 = '#8a7b8e'
seg3 = '#b0929e'
err  = '#74241f'
root = '#b0736c'
vim0 = '#543d08'
vim1 = '#5c3269'
vim2 = '#6b3413'

[username]
show_always = true
style_user = "bg:seg1 fg:fg0"
style_root = "bg:root fg:fg0"
format = '[$user]($style)'

[directory]
style = "fg:fg0 bg:seg2"
format = "[$path ]($style)"
truncation_length = 300
fish_style_pwd_dir_length = 1

[git_branch]
symbol = ""
format = '[$symbol $branch](fg:fg0 bg:seg3)'

[git_status]
format = '[($all_status$ahead_behind)](fg:fg0 bg:seg3)'

[character]
disabled = false
format = "$symbol"
success_symbol = '[󰛢 ](bg:seg1 bold fg:fg0)'
error_symbol = '[ ](bg:seg1 bold fg:red)'
vimcmd_symbol = '[](bg:seg1 bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bg:seg1 bold fg:color_seg3)'
vimcmd_replace_symbol = '[](bg:seg1 bold fg:color_seg3)'
vimcmd_visual_symbol = '[](bg:seg1 bold fg:color_yellow)'

[nix_shell]
disabled = false
impure_msg = ''
pure_msg = ''
unknown_msg = ''
format = '[$state ]($style)'
style = 'bg:seg4 fg:fg0'

[hostname]
disabled = false
ssh_only = false
ssh_symbol = '󰽧'#   󰤉 󰑱   󱎃     󰽧 󰽨 󰽥
format = '[@$hostname( $ssh_symbol)]($style)'
style = 'bg:seg1 fg:fg0'

[line_break]
disabled = true

[time]
disabled = true
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[os]
disabled = false

[nodejs]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cpp]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[php]
disabled = true

[java]
disabled = true

[kotlin]
disabled = true

[haskell]
disabled = true

[python]
disabled = true

[docker_context]
disabled = true

[conda]
disabled = true

[pixi]
disabled = true
